name: CI

on:
  push:
  # run weekly on main to ensure that main always has caches stored
  schedule:
    - cron: "0 0 * * SUN"

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    defaults:
      run:
        # use a login shell so that run steps will activate the venv
        shell: bash -e -o pipefail -l {0}
    env:
      PYTHON_VERSION: 3.8

    steps:
    - name: Lint PEP 8
      run: |
        pycodestyle
